### ISSUE TITLE
NullPointer Exception in vanilla updated Fiji

### ISSUE THREAD

**Issue by axtimwalde** [saalfeldlab/elm#9]
I just downloaded Fiji, updated completely and then tried to run ELM.  This fails showing this exception:
```
java.lang.NullPointerException
	at jitk.spline.ThinPlateR2LogRSplineKernelTransform.computeDeformationContribution(ThinPlateR2LogRSplineKernelTransform.java:871)
	at jitk.spline.ThinPlateR2LogRSplineKernelTransform.apply(ThinPlateR2LogRSplineKernelTransform.java:1047)
	at jitk.spline.ThinPlateR2LogRSplineKernelTransform.apply(ThinPlateR2LogRSplineKernelTransform.java:1027)
	at jitk.spline.ThinPlateR2LogRSplineKernelTransform.apply(ThinPlateR2LogRSplineKernelTransform.java:1090)
	at bdv.img.TpsTransformWrapper.applyInverse(TpsTransformWrapper.java:81)
	at net.imglib2.realtransform.InverseRealTransform.apply(InverseRealTransform.java:84)
	at net.imglib2.realtransform.RealTransformRealRandomAccessible$RealTransformRealRandomAccess.apply(RealTransformRealRandomAccessible.java:90)
	at net.imglib2.realtransform.RealTransformRealRandomAccessible$RealTransformRealRandomAccess.get(RealTransformRealRandomAccessible.java:96)
	at net.imglib2.realtransform.AffineRandomAccessible$AffineRandomAccess.get(AffineRandomAccessible.java:180)
	at net.imglib2.ui.SimpleInterruptibleProjector$1.run(SimpleInterruptibleProjector.java:167)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by bogovicj** [comment]
Was able to reproduce this. Thanks.

**Comment by axtimwalde** [comment]
@bogovicj @ctrueden @hinerm It is some version clash in the components.  Current BigWarp master works, but only after bumping to pom-fiji-21.1.0, with pom-fiji-21.0.0 it resulted in a non-starting ImageJ.

**Comment by bogovicj** [comment]
Ya, I noticed that imglib2 versions ("core", -ui, -realtransform, ) changed from pom-fiji 21.0.0 to 21.1.0, this seems promising...

**Comment by axtimwalde** [comment]
But what is in Fiji then?  Can you please investigate?

**Comment by bogovicj** [comment]
The versions in my "fresh & updated fiji" seem to agree with those in pom-fiji 21.1.0. 

Here's a diff of artifacts that bigwarp depends on that changed between those two pom-fiji's

```
< sc/fiji/bigwarp_fiji/2.0.1/bigwarp_fiji-2.0.1.jar
---
> sc/fiji/bigwarp_fiji/2.1.1/bigwarp_fiji-2.1.1.jar
3c3
< net/imglib2/imglib2-realtransform/2.0.0-beta-29/imglib2-realtransform-2.0.0-beta-29.jar
---
> net/imglib2/imglib2-realtransform/2.0.0-beta-30/imglib2-realtransform-2.0.0-beta-30.jar
8c8
< org/scijava/scijava-common/2.50.1/scijava-common-2.50.1.jar
---
> org/scijava/scijava-common/2.52.1/scijava-common-2.52.1.jar
14c14
< net/imglib2/imglib2-ui/2.0.0-beta-29/imglib2-ui-2.0.0-beta-29.jar
---
> net/imglib2/imglib2-ui/2.0.0-beta-30/imglib2-ui-2.0.0-beta-30.jar
18c18
< net/imagej/imagej-common/0.19.0/imagej-common-0.19.0.jar
---
> net/imagej/imagej-common/0.20.0/imagej-common-0.20.0.jar
22c22
< net/imglib2/imglib2/2.5.0/imglib2-2.5.0.jar
---
> net/imglib2/imglib2/2.6.0/imglib2-2.6.0.jar
```

**Comment by bogovicj** [comment]
Actually, I found something else - bigwarp_fiji-2.1.1 needs jitk-tps-2.0.0, but Fiji comes with an older tps: 1.3.1.

Updating jitk-tps seems to fix this issue for me.

**Comment by axtimwalde** [comment]
Hmmm,

who else is using jitk-tps?  I.e. whom will we break when jitk-tps is
upgraded?

If the answer is nobody, then can you upload the newest version?

Thanks,
Stephan

On Thu, 2016-03-03 at 10:18 -0800, John Bogovic wrote:
> Actually, I found something else - bigwarp_fiji-2.1.1 needs jitk-tps
> -2.0.0, but Fiji comes with an older tps: 1.3.1.
> Updating jitk-tps seems to fix this issue for me.
> —
> Reply to this email directly or view it on GitHub.
-- 

Stephan Saalfeld, Ph.D.
Group Leader
Janelia Research Campus
19700 Helix Drive | Ashburn, VA 20147
Phone: 571-209-4184 | Fax: 571-209-4946
saalfelds@janelia.hhmi.org

**Comment by bogovicj** [comment]
trakem2-tps also depends on it.  I can update that too though.

Double checked, and I'm not in the fiji uploaders group.  We talked to Mark about this
around the time of the ImageJ conference, but I didn't follow up, maybe because he uploaded bigwarp at the time.  I'll poke them again

**Comment by bogovicj** [comment]
related:
https://github.com/fiji/pom-fiji/pull/10
